name: Build and Deploy Swagger Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o ${{ github.workspace }}/output

    - name: Generate Swagger Documentation
      run: |
        dotnet tool install -g Swashbuckle.AspNetCore.Cli
        dotnet swagger tofile --output ${{ github.workspace }}/output/swagger.json ${{ github.workspace }}/output/QrCode-API.dll v1

    - name: Deploy Swagger Documentation to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ${{ github.workspace }}/output
